export {
	analyzeBacktest,
	BacktestAnalyticsError,
	BacktestError,
	buildBreakdowns,
	buildEquityCurve,
	calculateBacktestMetrics,
	DEFAULT_BACKTEST_EXECUTION_CONFIG,
	generateBacktestValidationReport,
	runBacktest
} from './backtest/index.js';
export type {
	BacktestAnalytics,
	BacktestBreakdownBucket,
	BacktestBreakdowns,
	BacktestErrorCode,
	BacktestExecutionConfig,
	BacktestInput,
	BacktestMetrics,
	BacktestRunResult,
	BacktestTrade,
	BacktestValidationReport,
	ClosedCandlePipeline,
	ClosedCandlePipelineResult,
	EquityCurvePoint,
	OpenBacktestTrade,
	PendingBacktestTrade,
	RunBacktestOptions,
	ValidationCheck,
	ValidationCheckStatus,
	ValidationVerdict
} from './backtest/index.js';
export {
	aggregateOneMinuteCandlesToFiveMinutes,
	assertValidCandle,
	CandleAggregationError,
	CandleValidationError,
	getCandleIdentity,
	getTimeframeDurationMilliseconds,
	mergeCandleBatches,
	sortCandlesChronologically,
	validateCandle
} from './market/index.js';
export type {
	Candle,
	CandleValidationIssue,
	CandleValidationIssueCode,
	CandleValidationResult,
	FiveMinuteAggregationResult,
	IncompleteFiveMinuteBucket,
	Timeframe
} from './market/index.js';
export { calculateRiskPlan, RiskCalculationError } from './risk/index.js';
export type { RiskCalculationInput, RiskConfig, RiskErrorCode, RiskPlan } from './risk/index.js';
export { classifySetupScore, scoreSetup } from './scoring/index.js';
export type {
	SetupClassification,
	SetupReason,
	SetupScoreResult,
	SetupScoringInput
} from './scoring/index.js';
export {
	AtrError,
	BosError,
	calculateTrueRange,
	calculateDealingRange,
	ChochError,
	classifyPremiumDiscount,
	createAtrState,
	createBosState,
	createChochState,
	createFvgState,
	createLiquidityState,
	createMarketStructureState,
	createOrderBlockState,
	detectConfirmedSwings,
	detectDisplacement,
	DisplacementError,
	FvgError,
	LiquidityDetectionError,
	LiquiditySweepError,
	MarketStructureError,
	OrderBlockError,
	PremiumDiscountError,
	processBosCandle,
	processAtrCandle,
	processChochCandle,
	processConfirmedSwing,
	processFvgCandle,
	processLiquiditySwing,
	processLiquiditySweepCandle,
	processOrderBlockCandle
} from './smc/index.js';
export type {
	AtrConfig,
	AtrProcessingResult,
	AtrState,
	AtrValue,
	BosProcessingResult,
	BosState,
	ChochProcessingResult,
	ChochState,
	DealingRange,
	DisplacementConfig,
	DisplacementEvent,
	FairValueGap,
	FvgProcessingResult,
	FvgState,
	LiquidityDetectionConfig,
	LiquidityInteraction,
	LiquidityInteractionType,
	LiquidityLevel,
	LiquidityProcessingResult,
	LiquiditySweep,
	LiquiditySweepProcessingResult,
	LiquidityState,
	MarketBias,
	MarketStructureState,
	MarketStructurePoint,
	OrderBlock,
	OrderBlockProcessingResult,
	OrderBlockState,
	PremiumDiscountZone,
	StructureBreak,
	StructureType,
	SwingDetectionConfig,
	SwingPoint
} from './smc/index.js';
export {
	CanonicalMinutePipelineError,
	createCanonicalMinutePipeline,
	createCanonicalMinutePipelineState,
	createSmcClosedCandlePipeline,
	createSmcClosedCandleState,
	createStrategyState,
	DEFAULT_SMC_STRATEGY_CONFIG,
	processCanonicalMinute,
	processSmcClosedCandle,
	processStrategySignal,
	StrategyStateError
} from './strategy/index.js';
export type {
	CanonicalMinutePipelineState,
	CanonicalMinuteProcessingResult,
	ChochSignal,
	DisplacementSignal,
	FvgSignal,
	HtfBiasSignal,
	InvalidationSignal,
	LiquiditySweepSignal,
	RetracementSignal,
	SetupDependencies,
	SMCStrategyConfig,
	SMCClosedCandlePipelineState,
	SMCClosedCandleTimeframeState,
	SMCSequenceContext,
	StrategyDirection,
	StrategyProcessingResult,
	StrategySignal,
	StrategyStage,
	StrategyState,
	StrategyTransition,
	TradingSetup
} from './strategy/index.js';
