export {
	analyzeBacktest,
	BacktestAnalyticsError,
	BacktestError,
	buildBreakdowns,
	buildEquityCurve,
	calculateBacktestMetrics,
	createValidationConfigHash,
	DEFAULT_BACKTEST_EXECUTION_CONFIG,
	generateBacktestValidationReport,
	InMemoryRealtimeIngestionAdapter,
	RealtimeIngestionError,
	runCanonicalReplayParity,
	runBacktest
} from './backtest/index.js';
export type {
	BacktestAnalytics,
	BacktestBreakdownBucket,
	BacktestBreakdowns,
	BacktestErrorCode,
	BacktestExecutionConfig,
	BacktestInput,
	BacktestMetrics,
	BacktestRunResult,
	BacktestTrade,
	BacktestValidationInput,
	BacktestValidationReport,
	CensoredOpenBacktestTrade,
	CanonicalReplayEvent,
	CanonicalReplayEventType,
	CanonicalReplayObservation,
	CanonicalReplayParityComparison,
	CanonicalReplayParityResult,
	ClosedCandlePipeline,
	ClosedCandlePipelineResult,
	EndOfRangeTerminalization,
	EquityCurvePoint,
	ExpiredPendingBacktestTrade,
	OpenBacktestTrade,
	PendingBacktestTrade,
	InMemoryRealtimeIngestionOptions,
	RealtimeIngestionErrorCode,
	RealtimeIngestionSnapshot,
	RealtimeParityDeliveryOptions,
	RunBacktestOptions,
	RunCanonicalReplayParityOptions,
	ValidationChronologicalSplit,
	ValidationCheck,
	ValidationCheckStatus,
	ValidationCostRun,
	ValidationCostScenario,
	ValidationMonthlyPeriod,
	ValidationOutlierConcentration,
	ValidationProvenance,
	ValidationRobustness,
	ValidationSegment,
	ValidationVerdict
} from './backtest/index.js';
export {
	aggregateOneMinuteCandlesToFiveMinutes,
	assertValidCandle,
	CANONICAL_CANDLES_PER_BIAS_CANDLE,
	CANONICAL_STRATEGY_TIMEFRAME,
	CandleAggregationError,
	CandleContinuityError,
	CandleValidationError,
	DERIVED_BIAS_TIMEFRAME,
	getCandleIdentity,
	getTimeframeDurationMilliseconds,
	isTimeframe,
	MILLISECONDS_PER_DAY,
	mergeCandleBatches,
	PRIMARY_MARKET_SYMBOL,
	prepareContinuousOneMinuteCandles,
	sortCandlesChronologically,
	TIMEFRAME_DURATION_MILLISECONDS,
	validateCandle
} from './market/index.js';
export type {
	Candle,
	CandleContinuityErrorCode,
	CandleValidationIssue,
	CandleValidationIssueCode,
	CandleValidationResult,
	FiveMinuteAggregationResult,
	IncompleteFiveMinuteBucket,
	OneMinuteContinuityRange,
	Timeframe
} from './market/index.js';
export { calculateRiskPlan, RiskCalculationError } from './risk/index.js';
export type { RiskCalculationInput, RiskConfig, RiskErrorCode, RiskPlan } from './risk/index.js';
export {
	classifyQualityScore,
	evaluateSetupEligibility,
	QUALITY_SCORE_BANDS,
	QUALITY_SCORE_MAX,
	QUALITY_SCORE_MIN,
	scoreSetupQuality
} from './scoring/index.js';
export type {
	EligibilityFailure,
	EligibilityInput,
	EligibilityResult,
	QualityScoreResult,
	QualityScoringInput,
	SetupClassification,
	SetupReason
} from './scoring/index.js';
export {
	AtrError,
	BosError,
	calculateTrueRange,
	calculateDealingRange,
	ChochError,
	classifyPremiumDiscount,
	createAtrState,
	createBosState,
	createChochState,
	createFvgState,
	createLiquidityState,
	createMarketStructureState,
	createOrderBlockState,
	detectConfirmedSwings,
	detectDisplacement,
	DisplacementError,
	FvgError,
	LiquidityDetectionError,
	LiquiditySweepError,
	MarketStructureError,
	OrderBlockError,
	PremiumDiscountError,
	processBosCandle,
	processAtrCandle,
	processChochCandle,
	processConfirmedSwing,
	processFvgCandle,
	processLiquiditySwing,
	processLiquiditySweepCandle,
	processOrderBlockCandle
} from './smc/index.js';
export type {
	AtrConfig,
	AtrProcessingResult,
	AtrState,
	AtrValue,
	BosProcessingResult,
	BosState,
	ChochProcessingResult,
	ChochState,
	DealingRange,
	DisplacementConfig,
	DisplacementEvent,
	ExpansionExtremeState,
	FairValueGap,
	FvgProcessingResult,
	FvgState,
	LiquidityDetectionConfig,
	LiquidityInteraction,
	LiquidityInteractionType,
	LiquidityLevel,
	LiquidityProcessingResult,
	LiquiditySweep,
	LiquiditySweepProcessingResult,
	LiquidityState,
	MarketBias,
	MarketStructureState,
	MarketStructurePoint,
	OrderBlock,
	OrderBlockProcessingResult,
	OrderBlockState,
	PremiumDiscountZone,
	ProtectedSwingState,
	StructureBreak,
	StructureType,
	SwingDetectionConfig,
	SwingPoint
} from './smc/index.js';
export {
	CanonicalMinutePipelineError,
	createCanonicalMinutePipeline,
	createCanonicalMinutePipelineState,
	createStrategyState,
	DEFAULT_SMC_STRATEGY_CONFIG,
	processCanonicalMinute,
	terminalizeCanonicalMinuteAtEndOfRange
} from './strategy/index.js';
export type {
	CanonicalMinuteEndOfRangeTerminalization,
	CanonicalMinutePipelineErrorCode,
	CanonicalMinutePipelineState,
	CanonicalMinuteProcessingResult,
	SetupDependencies,
	SMCStrategyConfig,
	StrategyDirection,
	StrategyStage,
	StrategyState,
	StrategyTransition,
	TradingSetup
} from './strategy/index.js';
